stages:
  - publish

variables:
  BUILD_TAG: $CI_COMMIT_TAG

publish-npm:
  stage: publish
  only: [tags]
  tags: [docker]
  image:
    name: node:lts-alpine
  script:
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_PUBLISH_TOKEN}"
    - sed -i -e "s/0.0.0-snapshot/$BUILD_TAG/g" package.json
    - cat package.json
    - npm publish --access public
