stages:
  - build
  - publish

variables:
  BUILD_TAG: $CI_COMMIT_TAG

image:
  name: node:lts-alpine
before_script:
  - sed -i -e "s/0.0.0-snapshot.1/$BUILD_TAG/g" package.json
  - yarn

build:
  stage: build
  tags: [docker]
  script: yarn build
  artifacts:
    paths:
      - lib/

publish-npm:
  stage: publish
  only: [tags]
  tags: [docker]
  script:
    - npm config set '//registry.npmjs.org/:_authToken' "${NPM_PUBLISH_TOKEN}"
    - npm publish --access public
